[DPE-4514] Add opensearch-benchmark-operator
canonical/opensearch-benchmark-operator pull request #2
Opened 2024-10-09 20:41 UTC by phvalguima

This PR adds the basis of OpenSearch Benchmark Operator.

The lifecycle of a benchmark run is the following:
1) The charm is deployed and related to OpenSearch
2) The user runs `prepare` action -> service file is rendered with the user's target workloads
3) The user executes `run` action -> the test starts following the user spec
4) `stop` action -> test stops
5) `clean` action -> data is cleaned and the service is cleaned.

The results will be available on prometheus.

-----------------------------------------------------------------------------------

## Models

There are two core models behind the scenes:
* DPBenchmarkBaseDatabaseModel: represents the data coming from the relation
* DPBenchmarkExecutionModel: represents the execution commands and should be 1-2-1 translation to the actual args; they will have a `DPBenchmarkBaseDatabaseModel` copy as part of its args

-----------------------------------------------------------------------------------

## Structure

It builds on top of the sysbench code base. However, most of its code has been refactored into the following structure:
* src/
  * benchmark/  -> common files that can (potentially) be reused across benchmark charms
* templates/ -> common templates such as service files

This charm follows closer to our new standard, by separating the concerns of managing the actual command, managing the relations and the final charm that aggregates all the components together.

2024-10-14 19:53 UTC, phvalguima commented on .github/workflows/ci.yaml
> +  # build:
TODO: I need to first merge this PR, then open a new PR on `charmcraftcache` repo to add the OSB charm there. Finally, we can build it with DPW.

2024-10-14 21:46 UTC, Mehdi-Bendriss requested changes
Thanks Pedro. This was not an easy PR to review.

1. The PR is too complicated and needs to be simplified. 
2. Abstractions need to be reduced to the bare minimum and only introduced when needed. Let's start small and generalize and extrapolate later.
3. Proxy methods need to be removed and additional components as well.
4. Many datastructures are confusing and redundant, prefer methods to enums as much as possible.
 
I believe we can get to the half of the current code base.

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +    def __del__(self):
Please don't rely on destructors. Exclusively rely on hooks. What are you trying to solve here?

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +    def is_tls_enabled(self):
When is this ever set to true? if never, let's drop.

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +        return self.model.get_binding(COS_AGENT_RELATION).network.bind_address
1. please put properties at the bottom of the module and should not be private. 
2. why are we relying on `COS_AGENT_RELATION` instead of the PEER relation ?

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +    def _on_config_changed(self, event):
type hinting missing for the event and return.

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +                self.stop()
missing return here? the new status will never be as set afterwards.

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +            if status in [DPBenchmarkExecStatus.RUNNING, DPBenchmarkExecStatus.ERROR]:
why do we need all these status checks, why not simply ".stop / .start"

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +    def _install_packages(self, extra_packages: List[str] = []):
please install additional packages as regular python dependencies of the charm, not in the code.

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +        self._install_packages(["python3-prometheus-client", "python3-jinja2", "unzip"])
same comment as above - on installing packages.

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +        self.SERVICE_CLS().render_service_executable()
I don't think we need this additional stage for the service.

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +            and self.benchmark_status.service_status()
app_status and service_status are confusing constructs. service_status is clear, pp_status is not.

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +        return None
the event argument is never used. 
This method is a proxy method, can be dropped and `self.benchmark_status.check()` directly used.

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +            event.fail("Failed: only leader can prepare the database")
status needs to be cleared.

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +        self.unit.status = ops.model.MaintenanceStatus("Checking status...")
I don't think this is needed to set.

2024-10-14 21:46 UTC, Mehdi-Bendriss commented on src/benchmark/benchmark_charm.py
> +            return
add a `finally` and clear status.

2024-10-15 07:01 UTC, phvalguima commented on config.yaml
> +      To set the test in Test mode or not.
So we can run it in CI. Otherwise samples will occupy several Gs of RAM.

There is also another advantage: `test-mode` generates quick bursts of benchmark

2024-10-15 07:02 UTC, phvalguima commented on src/benchmark/abs_benchmark_charm.py
> +class DPBenchmarkCharmInterface(ABC):
> This feels a bit too... Java-y 

Golang lessons, actually :D

2024-10-15 07:03 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +            if status in [DPBenchmarkExecStatus.RUNNING, DPBenchmarkExecStatus.ERROR]:
Because I use them to set the status of the charm on its end.

2024-10-15 07:07 UTC, phvalguima commented on .github/workflows/ci.yaml
> +  # build:
I can't right now. We cannot build without `charmcraftcache`.  I cannot merge https://github.com/canonical/charmcraftcache-hub/pull/112 without populating the `main` branch of this charm... So, to resolve this chicken-egg, here it goes:
1) Merge this PR
2) Merge the PR on charmcraft-hub
3) A new PR to the benchmark charm, adding int. tests (as we need a `build` for that)  and this build routine

2024-10-15 07:09 UTC, phvalguima commented on src/benchmark/abs_benchmark_charm.py
> +class DPBenchmarkCharmInterface(ABC):
The advantage: the next charmer coming to use this code (which I hope will happen), *must implement* the methods below or they will get a `NotImplementedError` exception

2024-10-16 06:07 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +        self.framework.observe(self.database.on.db_config_update, self._on_config_changed)
So, that `setup_db_relation` is the bit I am least sure what to do. It is there because sysbench can support both psql and mysql and I have to select accordingly.

2024-10-16 18:10 UTC, phvalguima commented on metadata.yaml
> +website: https://charmhub.io/sysbench
Updated or commented the ones we do not have yet. Filed a bug to return here: https://github.com/canonical/opensearch-benchmark-operator/issues/4

2024-10-16 19:38 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +    def __del__(self):
A single question: what is the message that is the most relevant to stay until the next hook happens. Nothing else happens.

I can only calculate this state at the end of this current hook.

2024-10-16 19:42 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +                self.stop()
No, that was on purpose. We had a service running and we have to stop before updating config.

2024-10-16 19:48 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +    def _install_packages(self, extra_packages: List[str] = []):
To clarify: this charm spins up a systemd service that also runs in python. This service uses system dependencies, including python dependencies.

I had tried multiple combinations here and not much success: 
* there is no such `stage-packages`
* there is no such `prime-packages`
* adding on `pyproject.toml` only assures the charm gets shipped with a given *python* dependency

2024-10-16 19:51 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +        self.SERVICE_CLS().render_service_executable()
The service comes as a python file in the `templates/` folder. It needs to be copied to the right place and a systemd service is set to manage the entire run.

Hence, I need it to do these operations.

2024-10-16 19:56 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +        if self.config.get("workload_name", "nyc_taxis") not in self.list_supported_workloads():
That is a good idea.

2024-10-17 08:26 UTC, phvalguima commented
Marking this time as we are changing the design of the charm to comply with existing standards

2024-10-17 08:35 UTC, phvalguima commented on src/benchmark/core/charm_interface.py
> +class DPBenchmarkCharmInterface(ABC):
Remove and transfer any non implemented method to the default_charm. Add an explanation on the README on why these methods are important to overload.

2024-10-17 08:38 UTC, phvalguima commented on src/benchmark/core/state.py
> +class BenchmarkState(ops.Object):
Agreed to review this on a following PR

2024-10-17 08:44 UTC, phvalguima commented on src/benchmark/default_charm.py
> +class DPDefaultBenchmarkCharm(ops.CharmBase, DPBenchmarkCharmInterface):
Rename to base charm

2024-10-17 08:45 UTC, phvalguima commented on src/benchmark/default_charm.py
> +    def __del__(self):
Move this logic to the `_update_status`.

2024-10-17 10:22 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +        self.framework.observe(self.database.on.db_config_update, self._on_config_changed)
The `setup_db_relation` is gone

2024-10-17 10:33 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +            event.fail("Failed: only leader can prepare the database")
Yes, now it does. I was originally counting on the `__del__` method.

2024-10-17 10:53 UTC, phvalguima commented
@Mehdi-Bendriss the list of files that you are missing to review and how they have been remapped:
* src/benchmark/service.py -> src/benchmark/events/service.py
* src/benchmark/status.py -> src/benchmark/core/state.py
* src/charm.py
* src/models.py -> src/literals.py
* src/opensearch_relation_manager.py -> copied into src/charm.py
* src/workload_parameter_templates/ -> these are json files with parameters coming from upstream
* templates/ -> script + systemd service file to be rendered

2024-10-17 10:55 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +            return
I need an `else` actually. added.

2024-10-17 10:56 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +        self.unit.status = ops.model.MaintenanceStatus("Checking status...")
Removed.

2024-10-17 10:56 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +            event.fail("Failed: only leader can prepare the database")
Extended the `self._set_status()` to be called at the end of each action.

2024-10-17 10:58 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +        return None
I prefer to keep this particular proxy method. It "decreases" the exception to a None OR result

2024-10-17 11:00 UTC, phvalguima commented on src/benchmark/benchmark_charm.py
> +                self.stop()
This IF check has been moved into `self.stop()`.

2024-10-21 15:31 UTC, marcoppenheimer commented on src/benchmark/core/state.py
> +        )
Also, here and generally, I don't think the typing is correct if we also return `None`. We'd want to make the return type `DPBenchmarkExecStatus | None`.

2024-10-21 15:31 UTC, marcoppenheimer commented on src/benchmark/core/state.py
> +    def app_status(self) -> DPBenchmarkExecStatus:
**nitpick/todo:** The typing here, and elsewhere in this file, is a bit wonky. I think here you want to return `DPBenchmarkExecStatus | None`

2024-10-21 15:31 UTC, marcoppenheimer commented on src/benchmark/core/state.py
> +    def app_status(self) -> DPBenchmarkExecStatus:
**todo:** I think the name of this field, `status`, is really ambiguous to the Juju unit/app status. It's also very vague as to what it should actually be doing, or what it's defined values are. Consider renaming it to something more descriptive and specific.

2024-10-21 15:31 UTC, marcoppenheimer commented on src/benchmark/core/state.py
**todo:** Overall, this `state` file is really clever! Though, I don't think it aligns too closely with the original intent for this. 

Generally, the `state` file is a collection of properties and 'combinations' of 'states' defined from the various peer-unit/app and client relations.
It's also missing a `models` file, where we define the structure of what we'd expect in the various relation-data bags. 

For examples from Kafka:

We have the `peer app-data` defined [here](https://github.com/canonical/kafka-operator/blob/61a42d7c6a8777229000004a959c47c9dac17e67/src/core/cluster.py#L226-L233), which instantiates a strongly typed [KafkaCluster](https://github.com/canonical/kafka-operator/blob/61a42d7c6a8777229000004a959c47c9dac17e67/src/core/models.py#L322-L407) object, which in turn inherits from [RelationState](https://github.com/canonical/kafka-operator/blob/61a42d7c6a8777229000004a959c47c9dac17e67/src/core/models.py#L47-L82).

I think Kafka's `RelationState` is similar to the `get` and `set` you have defined here, and I imagine that you wouldn't have much in that object other than `status`, but it's there you can type it with the values derived from `DPBenchmarkService`. Or better yet, you could co-opt `DPBenchmarkService` to be that `model` generally!

2024-10-21 15:31 UTC, marcoppenheimer commented on src/benchmark/core/state.py
> +        )
**praise:** This is exactly the sort of thing that we would call 'state', great stuff!
I think you can put it in the `model` for this though, similar to what we do in our `ZooKeeper` model for checking some condition (e.g [has all needed data been sent](https://github.com/canonical/kafka-operator/blob/61a42d7c6a8777229000004a959c47c9dac17e67/src/core/models.py#L679-L690))

2024-10-21 15:31 UTC, marcoppenheimer commented on src/benchmark/core/state.py
> +        return self.service_status()
**todo:** This is 'charm logic', as it's actually doing 'something' for the charm, and I don't believe this should be part of `state`. Consider moving this to `charm.py`.

2024-10-21 15:31 UTC, marcoppenheimer commented on src/benchmark/core/state.py
> +        return DPBenchmarkExecStatus.PREPARED
**todo:** Identical comment to the one above, this is definitely state, but as it's limitted only the what sits in app/unit data, it should go there.

2024-10-21 15:31 UTC, marcoppenheimer commented on src/benchmark/core/state.py
If you want, we can sit down and hack this out.

2024-10-21 15:31 UTC, marcoppenheimer commented on src/benchmark/events/db.py
**todo:** Let's try and keep this file limitted as much as possible to only event handlers, calling `state` and `managers/*` where needed. All the `check` or `relation_status` or `get_database_options` stuff can be put somewhere else, or put directly in the event handler if it's only used there.

2024-10-21 15:31 UTC, marcoppenheimer commented on src/benchmark/literals.py
> +    """
**todo:** These models are great, and should go in to `core/models.py`, maybe including the relation they belong to, so they can be typed abstractions to relation data.

2024-10-21 15:31 UTC, marcoppenheimer commented on src/benchmark/managers/service.py
**todo:** Have a look at what we're doing for Kafka's base [`core/workload`](https://github.com/canonical/kafka-operator/blob/main/src/core/workload.py) and the substrate-specific [`workload`](https://github.com/canonical/kafka-operator/blob/main/src/workload.py) that inherits from it. 

It's probably the most useful part of the pattern, as it allows for generalising operations on the underlying charm workload, but with different implementations for K8s + VM, and also making use of the all the various configuration paths.

2024-10-23 08:40 UTC, phvalguima commented on src/benchmark/core/state.py
> +    def app_status(self) -> DPBenchmarkExecStatus:
this file has been removed

2024-10-23 08:40 UTC, phvalguima commented on src/benchmark/core/state.py
this file has been removed

2024-10-23 08:40 UTC, phvalguima commented on src/benchmark/core/state.py
> +        )
this file has been removed

2024-10-23 08:40 UTC, phvalguima commented on src/benchmark/core/state.py
> +        return self.service_status()
this file has been removed

2024-10-23 08:41 UTC, phvalguima commented on src/benchmark/core/state.py
> +        return DPBenchmarkExecStatus.PREPARED
this file has been removed

2024-10-23 08:41 UTC, phvalguima commented on src/benchmark/literals.py
> +    """
this file has been removed

2024-10-23 08:41 UTC, phvalguima commented on src/benchmark/events/db.py
this file has been removed

2024-10-23 08:50 UTC, marcoppenheimer approved these changes

2024-10-23 08:50 UTC, marcoppenheimer commented on src/charm.py
> +class OpenSearchConfigManager(ConfigManager):
**non-blocking/thought:** I think down-the-line, we should find a place for these child classes that isn't getting in the way of `charm.py`, definitely makes it confusing. Low-hanging fruit, would be to add these to some `src/config.py` and src/models.py` or similar, where you inherit from the bases in `src/core/*`, similar to what we do with `workload`, and import them here, but this isn't something that should block this PR, just thoughts for the future.

2024-10-23 09:16 UTC, phvalguima commented on src/charm.py
> +class OpenSearchConfigManager(ConfigManager):
Agreed. I put it there simply because these were very tiny changes.

2024-10-23 09:22 UTC, reneradoi approved these changes
Given it is functional and after addressing Marc's review, I think the code is good to go as a v1.

There are some remarks that apply to the architecture and design in general. These don't have to be addressed in this PR, but they could be thought about in a later version:
- Regarding the installation/deployment of the benchmark tool: Instead of controlling a systemd service, the tool itself could be installed as a snap. This would avoid a lot of handling with the systemd service and the config file.
- Installing additional packages at runtime (of the charm) should be avoided, esp. from a security point of view. This could also be solved by providing the benchmark tool as a snap.
- The current design raises questions what would/should happen if the application is scaled up to more than one unit: running the exact same workload multiple times against the database, all writing to the same index might not be the desired behaviour.
- There is currently no real error handling, e.g. for cases like network interruption.
- Some security aspects should be reworked (e.g. password handling, accepting insecure connections).

2024-10-23 09:26 UTC, merged